import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {parseHTML} from '../.migration-rehearsal/node_modules/linkedom/esm/index.js';
import {createCustomers} from '../admin-customers.js';
const {document,window}=parseHTML(readFileSync(new URL('../admin.html',import.meta.url),'utf8'));
globalThis.document=document;
const $=id=>document.getElementById(id),tick=()=>new Promise(r=>setImmediate(r));
let checks=0,last,mode='normal',resolvePending;
const test=async(label,f)=>{await f();checks++;console.log('PASS '+label);};
const customer={id:'11111111-1111-4111-8111-111111111111',name:'<img src=x onerror=alert(1)>',phone:'9234567801',normal_orders:1,bulk_orders:0,last_order_at:'2026-09-20T18:45:00Z'};
const listing={customers:[customer],next_id:null};
const profile={customer,summary:{total_orders:1,normal_orders:1,bulk_orders:0,cancelled_or_rejected:0,preference_orders:1},addresses:[{address:'<script>bad()</script>',last_used:'2026-09-20T18:45:00Z'}],favourites:[{product_name:'Noodles',order_type:'normal',quantity:2}],hours:[{hour:0,orders:1}],orders:[{id:'1',order_number:'CBD-TEST',order_type:'normal',created_at:'2026-09-20T18:45:00Z',order_status:'new',payment_status:'pending',total:199,name:'Historic name',phone:customer.phone,address:'Test address',items:[{quantity:2,name:'Noodles'}]}],next_offset:null};
const ui=createCustomers(async body=>{last=body;if(mode==='pending')return new Promise(r=>resolvePending=r);if(mode==='error')throw new Error('Session expired');return body.action==='customers_list'?listing:profile;});
await test('customer names render as text without executable markup',async()=>{await ui.load();assert.ok($('customerList').textContent.includes(customer.name));assert.equal($('customerList').querySelectorAll('img').length,0);});
await test('profile shows contact, items, IST hours and safely rendered addresses',async()=>{$('customerList').querySelector('button').dispatchEvent(new window.Event('click'));await tick();assert.ok($('customerProfile').textContent.includes(customer.phone));assert.ok($('customerProfile').textContent.includes('00:00–00:59'));assert.ok($('customerProfile').textContent.includes('Limited history'));assert.equal($('customerProfile').querySelectorAll('script').length,0);assert.ok($('customerOrders').textContent.includes('2 × Noodles'));assert.equal($('customerOrdersNext').disabled,true);});
await test('search sends trimmed input and restarts customer pagination',async()=>{$('customerSearch').value='  9234567801  ';$('customerSearchForm').dispatchEvent(new window.Event('submit',{cancelable:true}));await tick();assert.equal(last.search,customer.phone);assert.equal(last.after_id,null);});
await test('sign-out reset clears customer contacts and order history',async()=>{ui.reset();for(const id of ['customerList','customerProfile','customerOrders'])assert.equal($(id).textContent,'');assert.equal($('customerDetail').hidden,true);});
await test('late list response cannot restore data after sign-out',async()=>{mode='pending';const p=ui.load();ui.reset();resolvePending(listing);await p;assert.equal($('customerList').textContent,'');});
await test('late profile response cannot restore data after sign-out',async()=>{mode='normal';await ui.load();mode='pending';$('customerList').querySelector('button').dispatchEvent(new window.Event('click'));ui.reset();resolvePending(profile);await tick();assert.equal($('customerProfile').textContent,'');assert.equal($('customerDetail').hidden,true);});
await test('API failures show a message without retaining list data',async()=>{mode='error';await ui.load();assert.equal($('customerMessage').textContent,'Session expired');assert.equal($('customerList').textContent,'');});
console.log(`${checks} customer DOM checks passed. Simulated API; real browser acceptance pending.`);
