import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {stripTypeScriptTypes} from 'node:module';
import vm from 'node:vm';
import {kitchenAttention} from '../kitchen-alerts.js';
import {parseHTML} from '../.migration-rehearsal/node_modules/linkedom/esm/index.js';
let checks=0;const test=async(label,f)=>{await f();checks++;console.log('PASS '+label);};
const now=Date.now(),stamp=new Date(now-6*60000).toISOString();
const summary={groups:[{order_type:'normal',count:1,oldest_at:stamp},{order_type:'bulk',count:1,oldest_at:stamp}]};
await test('both channels count and five-minute escalation use elapsed time',()=>{assert.deepEqual(kitchenAttention(summary,now),{total:2,normal:1,bulk:1,minutes:6,overdue:true});});
await test('invalid/missing alert responses cannot imply no waiting orders',()=>{for(const s of [null,{groups:[]},{groups:[summary.groups[0],summary.groups[0]]}])assert.throws(()=>kitchenAttention(s));});
let serve,calls=0,failed=false;
const rows=[...Array.from({length:200},(_,i)=>({id:'n'+i,created_at:new Date(now-i*1000).toISOString(),order_status:'delivered',acknowledged_at:stamp})),{id:'old',created_at:stamp,order_status:'new',acknowledged_at:null}];
const client={rpc:async()=>({data:true}),from(table){let data=table==='normal_orders'?rows:table==='bulk_orders'?[{id:'b',created_at:stamp,order_status:'new',acknowledged_at:null}]:[],counted=false,ascending=false;
 const q={select(fields,opt){counted=!!opt?.count;return q;},eq(k,v){data=data.filter(r=>r[k]===v);return q;},is(k,v){data=data.filter(r=>r[k]===v);return q;},order(k,opt){ascending=opt.ascending;return q;},in(){return q;},limit(n){if(failed&&counted)return Promise.resolve({error:{message:'injected'}});return Promise.resolve({data:[...data].sort((a,b)=>(ascending?1:-1)*(Date.parse(a.created_at)-Date.parse(b.created_at))).slice(0,n),count:counted?data.length:null});},then(fn){return Promise.resolve({data:[]}).then(fn);}};return q;}};
const env={SUPABASE_URL:'offline',SUPABASE_ANON_KEY:'anon',SUPABASE_SERVICE_ROLE_KEY:'service',TCB_ADMIN_EMAIL:'owner@example.com'};
const src=stripTypeScriptTypes(readFileSync(new URL('../supabase/functions/admin-orders/index.ts',import.meta.url),'utf8').replace(/^import .*createClient.*;$/m,''));
vm.runInNewContext(src,{Deno:{env:{get:k=>env[k]},serve:f=>serve=f},createClient:(u,key)=>{if(key==='service'){calls++;return client;}return {auth:{getUser:async token=>({data:{user:token==='anon'?null:{id:'admin',email:token==='owner'?'owner@example.com':'other@example.com'}}})}};},Request,Response,TextEncoder,TextDecoder,crypto,console:{error(){},warn(){}}});
const call=(token,body)=>serve(new Request('https://offline.invalid',{method:'POST',headers:{'content-type':'application/json',...(token?{authorization:'Bearer '+token}:{})},body:JSON.stringify(body)}));
await test('alert counts require verified admin identity',async()=>{for(const [token,status] of [[null,401],['anon',401],['other',403]])assert.equal((await call(token,{action:'list',include_attention:true})).status,status);assert.equal(calls,0);});
await test('old unattended orders count beyond the recent-list limit',async()=>{const r=await call('owner',{action:'list',order_type:'all',limit:1,include_attention:true});assert.equal(r.status,200);const d=await r.json();assert.equal(d.orders.length,1);assert.equal(d.orders[0].id,'n0');assert.equal(kitchenAttention(d.attention).total,2);});
await test('attention view returns waiting orders instead of newer completed orders',async()=>{const d=await (await call('owner',{action:'list',order_type:'all',needs_attention:true,limit:10})).json();assert.deepEqual(d.orders.map(o=>o.id).sort(),['b','old']);});
await test('failed count query reports failure, never zero pending orders',async()=>{failed=true;assert.equal((await call('owner',{action:'list',include_attention:true})).status,500);failed=false;});
const html=readFileSync(new URL('../orders.html',import.meta.url),'utf8');
const {document,window}=parseHTML(html);window.TCB_SUPABASE_CONFIG={url:'offline',anonKey:'anon',adminOrdersUrl:'https://offline.invalid'};
const timers=new Map();let timer=0,pending,mode='ok',beeps=0;
window.AudioContext=class {state='running';currentTime=0;destination={};createOscillator(){beeps++;return {frequency:{},connect(){return {connect(){}}},start(){},stop(){}};}createGain(){return {gain:{setValueAtTime(){},exponentialRampToValueAtTime(){}}};}};
const context={window,document,kitchenAttention,createClient:()=>({auth:{getSession:async()=>({data:{session:{access_token:'owner'}}}),onAuthStateChange(){},signOut:async()=>{}}}),localStorage:{setItem(){}},setInterval:f=>{timers.set(++timer,f);return timer;},clearInterval:id=>timers.delete(id),setTimeout:()=>0,clearTimeout(){},Date,console:{error(){},warn(){}},AbortSignal,fetch:async()=>{if(mode==='pending')return new Promise(r=>pending=r);if(mode==='error')throw new Error('offline');return {ok:true,json:async()=>({success:true,orders:[],attention:summary})};}};
let script=html.match(/<script type="module">([\s\S]*?)<\/script>/)[1].replace(/^\s*import .*;$/gm,'');
script=script.replace(/    const \{ data: initial \} = await client.auth.getSession\(\);\s*await showApp\(initial.session\);/,'globalThis.qa={showApp,refreshOrders,enableSound,disableSound,updateAlarm};');
vm.createContext(context);vm.runInContext(script,context);
await test('visual alerts work without sound permission',async()=>{await context.qa.showApp({});assert.ok(document.getElementById('attentionBanner').classList.contains('visible'));assert.equal(beeps,0);assert.match(document.title,/2/);});
await test('sound is explicit and polling does not restart alarm each refresh',async()=>{await context.qa.enableSound();assert.ok(beeps>0);const before=beeps;await context.qa.refreshOrders();assert.equal(beeps,before);});
await test('connection failure stops repeating sound and warns staff',async()=>{mode='error';await context.qa.refreshOrders();assert.match(document.getElementById('kitchenAlertStatus').textContent,/unavailable/);assert.equal(timers.size,1);});
await test('late refresh cannot restore orders, title or timers after sign-out',async()=>{mode='pending';const p=context.qa.refreshOrders();await context.qa.showApp(null);pending({ok:true,json:async()=>({success:true,orders:[],attention:summary})});await p;assert.equal(document.title,'Order Console | The Chinese Bliss');assert.equal(timers.size,0);assert.equal(document.getElementById('ordersList').textContent,'');});
console.log(`${checks} kitchen alert API/DOM checks passed. Mock API/audio; live acceptance pending.`);
