-- The Chinese Bliss — website order-system security hardening
-- Apply AFTER 20260916_order_operations.sql.
--
-- Security goals:
-- 1) Browser roles cannot directly read/change customer/order/audit data.
-- 2) Only Edge Functions using the server secret/service role perform writes.
-- 3) Public order/status APIs have a server-side rate-limit primitive.
-- 4) Idempotency keys cannot create duplicate orders during request races.

begin;

-- ---------------------------------------------------------------------
-- Sensitive tables: no direct Data API access from browser roles.
-- Edge Functions use the server-side service role / secret key.
-- ---------------------------------------------------------------------
do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'customers',
    'normal_orders',
    'normal_order_items',
    'bulk_orders',
    'bulk_order_items',
    'order_status_events'
  ]
  loop
    if to_regclass('public.' || table_name) is not null then
      execute format('alter table public.%I enable row level security', table_name);
      execute format('revoke all privileges on table public.%I from anon', table_name);
      execute format('revoke all privileges on table public.%I from authenticated', table_name);
    end if;
  end loop;
end $$;

-- Products may be public catalogue data, but customers must never be able
-- to modify prices or availability from a browser/mobile client.
do $$
begin
  if to_regclass('public.products') is not null then
    alter table public.products enable row level security;
    revoke insert, update, delete, truncate, references, trigger on table public.products from anon, authenticated;
  end if;
end $$;

-- ---------------------------------------------------------------------
-- Race-safe idempotency.
-- Fail visibly during deployment if historical duplicate keys already
-- exist, rather than silently leaving the system vulnerable to duplicates.
-- ---------------------------------------------------------------------
do $$
begin
  if to_regclass('public.normal_orders') is not null then
    if exists (
      select idempotency_key
      from public.normal_orders
      where idempotency_key is not null
      group by idempotency_key
      having count(*) > 1
    ) then
      raise exception 'Duplicate normal_orders.idempotency_key values must be resolved before security hardening.';
    end if;
    create unique index if not exists normal_orders_idempotency_unique
      on public.normal_orders (idempotency_key)
      where idempotency_key is not null;
  end if;

  if to_regclass('public.bulk_orders') is not null then
    if exists (
      select idempotency_key
      from public.bulk_orders
      where idempotency_key is not null
      group by idempotency_key
      having count(*) > 1
    ) then
      raise exception 'Duplicate bulk_orders.idempotency_key values must be resolved before security hardening.';
    end if;
    create unique index if not exists bulk_orders_idempotency_unique
      on public.bulk_orders (idempotency_key)
      where idempotency_key is not null;
  end if;
end $$;

-- ---------------------------------------------------------------------
-- Server-only audit log for non-status admin actions.
-- ---------------------------------------------------------------------
create table if not exists public.order_admin_events (
  id bigint generated by default as identity primary key,
  order_type text not null check (order_type in ('normal', 'bulk')),
  order_id text not null,
  order_number text,
  action text not null,
  changed_by text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.order_admin_events enable row level security;
revoke all privileges on table public.order_admin_events from anon, authenticated;
create index if not exists order_admin_events_order_idx
  on public.order_admin_events (order_type, order_id, created_at desc);

-- ---------------------------------------------------------------------
-- Atomic fixed-window rate limiting used only by Edge Functions.
-- No raw IP address is stored; functions send a SHA-256 key.
-- ---------------------------------------------------------------------
create table if not exists public.tcb_security_rate_limits (
  scope text not null,
  key_hash text not null,
  window_start timestamptz not null,
  request_count integer not null default 1 check (request_count > 0),
  primary key (scope, key_hash, window_start)
);

alter table public.tcb_security_rate_limits enable row level security;
revoke all privileges on table public.tcb_security_rate_limits from anon, authenticated;

create or replace function public.tcb_consume_rate_limit(
  p_scope text,
  p_key_hash text,
  p_limit integer,
  p_window_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_window_start timestamptz;
  v_count integer;
begin
  if p_scope is null or length(p_scope) < 1 or length(p_scope) > 80 then
    raise exception 'invalid rate limit scope';
  end if;
  if p_key_hash is null or length(p_key_hash) <> 64 then
    raise exception 'invalid rate limit key';
  end if;
  if p_limit < 1 or p_limit > 10000 or p_window_seconds < 1 or p_window_seconds > 86400 then
    raise exception 'invalid rate limit parameters';
  end if;

  v_window_start := to_timestamp(
    floor(extract(epoch from clock_timestamp()) / p_window_seconds) * p_window_seconds
  );

  insert into public.tcb_security_rate_limits(scope, key_hash, window_start, request_count)
  values (p_scope, p_key_hash, v_window_start, 1)
  on conflict (scope, key_hash, window_start)
  do update set request_count = public.tcb_security_rate_limits.request_count + 1
  returning request_count into v_count;

  return v_count <= p_limit;
end;
$$;

revoke all on function public.tcb_consume_rate_limit(text, text, integer, integer) from public, anon, authenticated;
grant execute on function public.tcb_consume_rate_limit(text, text, integer, integer) to service_role;

commit;
